dielectric_constants:
  DIELECTRIC: 11.0
  HELIUM: 1.057
  METAL: 1.0
  VACUUM: 1.0
extract_opt:
- additional_name: TransferDevice
  coordinate1:
  - -10
  - 5
  - 1001
  coordinate2:
  - 0
  - 50
  - 201
  coordinate3: 1.21
  plane: xy
  quantity: phi
ff_polynomial: 2
meshfile: dump/TransferDevice
physicalSurfaces:
  Barrier: 5
  Door1: 8
  Door2: 11
  Reservoir: 9
  Sense: 7
  ThinFilm: 6
  Top: 12
  Twiddle: 10
physicalVolumes:
  DIELECTRIC: 2
  HELIUM: 1
  METAL: 3
  VACUUM: 4
